# Generated by Django 2.2.16 on 2022-03-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20220317_2116"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_following",
        ),
    ]
