# Generated by Django 2.2.16 on 2022-03-17 22:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20220318_0107"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="cant_following_yourself",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True, following=django.db.models.expressions.F("user")
                ),
                name="cant_following_yourself",
            ),
        ),
    ]
